# Import dataset using pandas and fill the Postgres

In [1]:
# Import libraries

import pandas as pd
import matplotlib.pyplot as plt
import sqlalchemy

In [54]:
# Creating engine

engine = sqlalchemy.create_engine("postgresql+psycopg2://admin:admin@127.0.0.1:5433/postgres")

with engine.connect() as conn:
    print("Successful")

Successful

In [58]:
# Reading dataset

df = pd.read_csv("dataset/exchange_rates.csv", index_col=0)

df['date'] = pd.to_datetime(df['date'], format="%d/%m/%Y")

df.head()

      Country/Currency currency       value       date
0     Australia Dollar      AUD    1.581627 2021-12-17
1  Great Britain Pound      GBP    0.851619 2021-12-17
2                 Euro      EUR    1.000000 2021-12-17
3            Japan Yen      JPY  128.301759 2021-12-17
4    Switzerland Franc      CHF    1.041015 2021-12-17

In [59]:
# Filtering the data. We will work with USD, RUB, CNY

dfRUB = df[df['currency'].isin(['RUB', 'USD', 'CNY'])]
dfRUB = dfRUB.rename(columns={'Country/Currency': 'country'})

dfRUB.describe()

             value                        date
count  3979.000000                        3979
mean     31.839402  2023-10-11 02:51:32.435285
min       0.959445         2021-12-17 00:00:00
25%       1.098357         2022-11-12 00:00:00
50%       7.600450         2023-10-10 00:00:00
75%      79.064595         2024-09-05 00:00:00
max     150.200086         2025-10-27 00:00:00
std      41.149126                         NaN

In [17]:
# Creating tables

with engine.connect() as conn:
    conn.execute(sqlalchemy.text("""
        CREATE TABLE IF NOT EXISTS exchange_rates (
            id SERIAL PRIMARY KEY,
            country VARCHAR(100),
            currency VARCHAR(100),
            value NUMERIC,
            date DATE
        )
    """))
    conn.commit()

In [69]:
# Filling the table

with engine.connect() as conn:
    dfRUB.to_sql('exchange_rates', engine, if_exists='append', index=False)

    print(result.fetchall())

[]

In [71]:
# Checking table

with engine.connect() as conn:
    result = conn.execute(sqlalchemy.text("""
    SELECT country, avg(value) FROM exchange_rates GROUP BY country LIMIT 10
    """))
    print(result.fetchall())

[('USA Dollar', Decimal('1.0841643328601845')), ('Russia Rouble', Decimal('89.8458503175097276')), ('China Yuan/Renminbi', Decimal('7.5560112404669261'))]