In [1]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlalchemy
from sqlalchemy import text

In [4]:
# Creating engine

engine = sqlalchemy.create_engine("postgresql+psycopg2://admin:admin@127.0.0.1:5433/postgres")

with engine.connect() as conn:
    print("Successful")

Successful

In [7]:
query = """
select country, avg(value) as value, extract(month from date) as month, extract(year from date) as year from exchange_rates group by month, year, country order by year, month
"""

df = pd.read_sql(query, engine)
df['date'] = pd.to_datetime(df[['month', 'year']].assign(day=1))

print(df.head(10))
df.describe()

               country       value  month    year       date
0           USA Dollar    1.130525   12.0  2021.0 2021-12-01
1        Russia Rouble   83.537984   12.0  2021.0 2021-12-01
2  China Yuan/Renminbi    7.203924   12.0  2021.0 2021-12-01
3  China Yuan/Renminbi    7.197490    1.0  2022.0 2022-01-01
4        Russia Rouble   86.606682    1.0  2022.0 2022-01-01
5           USA Dollar    1.132573    1.0  2022.0 2022-01-01
6  China Yuan/Renminbi    7.192350    2.0  2022.0 2022-02-01
7           USA Dollar    1.133727    2.0  2022.0 2022-02-01
8        Russia Rouble   88.198948    2.0  2022.0 2022-02-01
9        Russia Rouble  120.975622    3.0  2022.0 2022-03-01

            value       month         year                        date
count  133.000000  133.000000   133.000000                         133
mean    31.840167    6.278195  2023.285714  2023-09-22 10:06:18.947368
min      0.983120    1.000000  2021.000000         2021-12-01 00:00:00
25%      1.100746    3.000000  2022.000000         2022-11-01 00:00:00
50%      7.603805    6.000000  2023.000000         2023-10-01 00:00:00
75%     78.761254    9.000000  2024.000000         2024-09-01 00:00:00
max    120.975622   12.000000  2025.000000         2025-10-01 00:00:00
std     41.178815    3.488842     1.104889                         NaN

In [70]:
# The ratio of the ruble exchange rates between 2021 and 2025

with engine.connect() as conn:
    result = pd.read_sql(sqlalchemy.text("""
    select (select value from exchange_rates where country = 'Russia Rouble' order by date asc limit 1)::float / (select value from exchange_rates where country = 'Russia Rouble' order by date desc limit 1) as relationship
"""), conn)

    print(result.to_string(index=False))

 relationship
     0.926386

In [76]:
# Average exchange rates of the ruble through years

with engine.connect() as conn:
    result = pd.read_sql(sqlalchemy.text("""
    select avg(value) as RUB, extract(year from date) as year from exchange_rates where country = 'Russia Rouble' group by year order by year
"""), conn)

    print(result.to_string(index=False))

       rub   year
 83.537984 2021.0
 74.329701 2022.0
 92.392264 2023.0
100.379868 2024.0
 95.560515 2025.0

In [115]:
# Average deviation exchange rates of the ruble in the 2024

with engine.connect() as conn:
    result = pd.read_sql(sqlalchemy.text("""
    select avg(value) as average,
    round(abs(avg(value) - (select avg(value) from exchange_rates where extract(year from date) = 2024 and country = 'Russia Rouble')) / (select avg(value) from exchange_rates where extract(year from date) = 2024 and country = 'Russia Rouble') * 100, 4) || '%' as deviation,
    to_char(date, 'Month') as month,
    extract(month from date) as monthNum
    from exchange_rates
    where country = 'Russia Rouble' and extract(year from date) = 2024
    group by monthNum, month
    order by monthNum
"""), conn)

    print(result.to_string(index=False))

   average deviation     month  monthnum
 97.645572   2.7239% January         1.0
 99.028548   1.3462% February        2.0
 99.818709   0.5590% March           3.0
 99.801435   0.5762% April           4.0
 98.686910   1.6866% May             5.0
 95.088298   5.2715% June            6.0
 94.743868   5.6147% July            7.0
 97.889856   2.4806% August          8.0
101.388490   1.0048% September       9.0
104.883807   4.4869% October        10.0
107.069137   6.6640% November       11.0
108.485572   8.0750% December       12.0

In [161]:
# Average deviation exchange rates of the ruble in the 2024

with engine.connect() as conn:
    result = pd.read_sql(sqlalchemy.text("""
    select deviation, month from (
    select avg(value) as average,
    round(abs(avg(value) - (select avg(value) from exchange_rates where extract(year from date) = 2024 and country = 'Russia Rouble')) / (select avg(value) from exchange_rates where extract(year from date) = 2024 and country = 'Russia Rouble') * 100, 4) || '%' as deviation,
    to_char(date, 'Month') as month,
    extract(month from date) as monthNum
    from exchange_rates
    where country = 'Russia Rouble' and extract(year from date) = 2024
    group by monthNum, month
    order by monthNum
    )
"""), conn)

    print(result.to_string(index=False))

deviation     month
  2.7239% January
  1.3462% February
  0.5590% March
  0.5762% April
  1.6866% May
  5.2715% June
  5.6147% July
  2.4806% August
  1.0048% September
  4.4869% October
  6.6640% November
  8.0750% December

In [162]:
df

               country        avg
0           USA Dollar   1.084164
1        Russia Rouble  89.845850
2  China Yuan/Renminbi   7.556011